### PR TITLE
Fix Standardize Translations

### LINKED ISSUE #113: Standardize Translations
Textdomains vary throughout the plugin -- they all need to match. Also need a new pot file.

### PR DESCRIPTION
**Pull request by Ritesh-patel**
Fixes #113

- Set text domain to "solr-for-wordpress-on-pantheon"
- Add missing text domain

### CODE REVIEW

File: includes/legacy-functions.php [hunk 1]
```diff
@@ -295,16 +295,16 @@ function s4wp_print_facet_items( $items, $pre = "<ul>", $post = "</ul>", $before
...
-		printf( __( "%s<a href=\"%s\">%s (%s)</a>%s\n" ), $before, $item[ "link" ], $item[ "name" ], $item[ "count" ], $after );
+		printf( __( "%s<a href=\"%s\">%s (%s)</a>%s\n", 'solr-for-wordpress-on-pantheon' ), $before, $item[ "link" ], $item[ "name" ], $item[ "count" ], $after );
 		$item_items = isset( $item[ "items" ] ) ? true : false;
 
 		if ( $item_items ) {
 			s4wp_print_facet_items( $item[ "items" ], $nestedpre, $nestedpost, $nestedbefore, $nestedafter, $nestedpre, $nestedpost, $nestedbefore, $nestedafter );
 		}
 	}
-	printf( __( "%s\n" ), $post );
+	printf( __( "%s\n", 'solr-for-wordpress-on-pantheon' ), $post );
```
Comment (ataylorme) [inline includes/legacy-functions.php]: There is nothing to translate here, I think this can simply be _printf_

File: includes/legacy-functions.php [hunk 2]
```diff
@@ -10,23 +10,23 @@ function s4wp_search_form() {
...
-		$sortval = __( '<option value="score" selected="selected">Score</option><option value="date">Date</option><option value="modified">Last Modified</option>' );
+		$sortval = __( '<option value="score" selected="selected">Score</option><option value="date">Date</option><option value="modified">Last Modified</option>', 'solr-for-wordpress-on-pantheon' );
 	}
 
 	if ( $order == 'asc' ) {
-		$orderval = __( '<option value="desc">Descending</option><option value="asc" selected="selected">Ascending</option>' );
+		$orderval = __( '<option value="desc">Descending</option><option value="asc" selected="selected">Ascending</option>', 'solr-for-wordpress-on-pantheon' );
 	} else {
-		$orderval = __( '<option value="desc" selected="selected">Descending</option><option value="asc">Ascending</option>' );
+		$orderval = __( '<option value="desc" selected="selected">Descending</option><option value="asc">Ascending</option>', 'solr-for-wordpress-on-pantheon' );
```
Comment (ataylorme) [inline includes/legacy-functions.php]: We shouldn't include HTML in translations unless it is necessary. Please reformat instances like this to:

```php
$orderval = '<option value="desc" selected="selected">' . __( 'Descending', 'solr-for-wordpress-on-pantheon' ) . '<option value="asc">' . __( 'Ascending', 'solr-for-wordpress-on-pantheon' ) . '</option>';
```

or use _wp_kses()_ as [suggested by the Codex](https://codex.wordpress.org/I18n_for_WordPress_Developers#HTML)

File: solr-power.php [hunk 3]
```diff
@@ -6,6 +6,7 @@
   Version: 0.5.0
   Author: Pantheon
   Author URI: http://pantheon.io
+  Text Domain: solr-for-wordpress-on-pantheon
  */
 /*
   Copyright (c) 2011 Matt Weber
```
Comment (ataylorme) [inline solr-power.php]: Let's update this to Pantheon as well.

File: includes/legacy-functions.php (hunk 1 above)
Comment (Ritesh-patel) [inline includes/legacy-functions.php]: I just added text domain in all such strings. I will be removing it from all such strings.

File: solr-power.php (hunk 3 above)
Comment (Ritesh-patel) [inline solr-power.php]: @ataylorme can you clarify what you mean?

Comment (ataylorme) [inline solr-power.php]: @Ritesh-patel The copyright line says "Matt Weber"

File: includes/legacy-functions.php (hunk 2 above)
Comment (Ritesh-patel) [inline includes/legacy-functions.php]: Option 1 seems fine to me.

Comment (ataylorme) [inline includes/legacy-functions.php]: Great - please find and update all similar instances with HTML in the translation string and separate the HTML from the translatable text.

Comment (Ritesh-patel) [inline includes/legacy-functions.php]: Updated.

File: solr-power.php (hunk 3 above)
Comment (Ritesh-patel) [inline solr-power.php]: Updated.

**Comment by ataylorme** [comment]
@Ritesh-patel thank you for the timely updates! I'll do a final test of the branch then hopefully merge this week.
