### PR TITLE
POST actions to `admin.php` in network admin too

### LINKED ISSUE #317: Multisite: Wrong menu highlighted after running an action
After clicking an action button on `/wp-admin/network/admin.php?page=solr-power#top#solr_action` you get redirected to `/wp-admin/network/settings.php?page=solr-power#top#solr_action` and the "Settings" menu is highlighted.

solr

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #317

### CODE REVIEW

File: solr-options-page.php [hunk 1]
```diff
@@ -51,11 +51,7 @@
 
 
 		<?php
-		if ( is_multisite() ) {
-			$action = 'settings.php?page=solr-power';
-		} else {
-			$action = 'admin.php?page=solr-power';
-		}
+		$action = is_multisite() ? network_admin_url( 'admin.php?page=solr-power' ) : admin_url( 'admin.php?page=solr-power' );
```
Comment (ocean90) [inline solr-options-page.php]: This could be changed to use `self_admin_url()`.

**Comment by danielbachhuber** [comment]
@ataylorme Updated in 7d024f3b787c50f60f5bafa650dbdc195dbd5508

In the future, feel free to edit the pull request directly for minor changes like this.

**Comment by danielbachhuber** [comment]
@ataylorme Anything else need to be done here?
