### PR TITLE
Error early when `PANTHEON_ENVIRONMENT` isn't set

### LINKED ISSUE #230: Inconsistent user experience for submitting a schema
When I repost schema.xml through the WordPress admin, I see:

image

When I repost schema.xml through WP-CLI, I see:

```
$ wp solr repost-schema
Error: Schema repositing only works in a Pantheon environment.
```

In both cases, I'd expect to be able to repost my schema.xml. If it's not technically feasible, I'd expect to see some better error message communicating what I should do instead.

### PR DESCRIPTION
**Pull request by danielbachhuber**
Schema posting only works on Pantheon

Fixes #230

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Looks like this: 
image

File: includes/class-solrpower-options.php [hunk 1]
```diff
@@ -354,6 +354,10 @@ function check_for_actions() {
 				if ( ! $this->check_nonce( 'solr_repost_schema' ) ) {
 					return;
 				}
+				if ( ! getenv( 'PANTHEON_ENVIRONMENT' ) || ! getenv( 'FILEMOUNT' ) ) {
+					$this->msg = esc_html__( 'Schema repositing only works in a Pantheon environment.', 'solr-for-wordpress-on-pantheon' );
+					break;
```
Comment (ataylorme) [inline includes/class-solrpower-options.php]: Typo? _repositing_ should be _reposting_

Comment (danielbachhuber) [inline includes/class-solrpower-options.php]: 8eaf334
